# Site Settings
title:               section 01
tagline:             a website
description:
baseurl:            ""
url:                "https://sylph01.github.io/"
github:
  url:               ""
author:
  name:              "sylph01"
  email:             "sylph01@gmail.com"
  twitter:           "s01"
  github:            "sylph01"
navigation:
- title: About
  url: /menu/about
- title: Articles
  url: /menu/articles
- title: Blog(ja)
  url: "http://sylph01.hatenablog.jp/"

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
