# Site Settings
title:               section 01
tagline:             a website
description:
baseurl:            ""
url:                "https://s01.ninja"
github:
  url:               ""
author:
  name:              "sylph01"
  email:             "sylph01@gmail.com"
  twitter:           "s01"
  github:            "sylph01"
navigation:
- title: Articles(ja)
  url: /menu/articles_ja
- title: Articles(en)
  url: /menu/articles_en
- title: Blog(ja)
  url: "http://sylph01.hatenablog.jp/"
- title: About
  url: /about

paginate:            5ex
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
# gems:              [jekyll-paginate]

timezone:            Asia/Tokyo
